/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jvm_tech_demonlee_jni_FooNative */

#ifndef _Included_jvm_tech_demonlee_jni_FooNative
#define _Included_jvm_tech_demonlee_jni_FooNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jvm_tech_demonlee_jni_FooNative
 * Method:    bar
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_jvm_tech_demonlee_jni_FooNative_bar
  (JNIEnv *, jobject, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
